# Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "postgres:alpine"
        args: [ "-c", "max_connections=1000" ]
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: app-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---

# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres

---

# Postgres PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql

---

# Postgres PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

# Spring Boot Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: ghcr.io/egargo/egargo.spring-boot-crud-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 28279
          envFrom:
          - secretRef:
              name: app-secret

---

# Spring Boot Service
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  type: NodePort
  ports:
    - port: 28279
  selector:
    app: spring-boot
