services:
    spring-db:
        image: postgres:alpine
        container_name: egargo.spring-boot-crud-db
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_DB}
          - PGPORT=${DATABASE_PORT}
        command: postgres -c 'max_connections=1000'
        ports:
            - ${DATABASE_PORT}:5432
        expose:
            - ${DATABASE_PORT}
        volumes:
            - spring-boot-crud-data:/var/lib/postgresql

    keycloak:
        image: quay.io/keycloak/keycloak:25.0.4
        container_name: egargo.spring-boot-keycloak
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        # command: kc.sh start-dev
        command: start-dev
        ports:
            - 8080:8080

    spring-boot:
        image: ghcr.io/egargo/egargo.spring-boot-crud-app
        container_name: egargo.spring-boot-crud-app
        build:
            context: .
        ports:
            - 28279:28279
        depends_on:
            - spring-db
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

volumes:
    spring-boot-crud-data:
