services:
    spring-db:
        image: postgres
        container_name: clint-don.spring-boot-crud-db
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
          - PGPORT=${PGPORT}
        command: postgres -c 'max_connections=1000'
        ports:
            - 5433:5432
        expose:
            - 5433
        volumes:
            - spring-boot-crud-data:/var/lib/postgresql

    spring-boot:
        image: ghcr.io/egargo/clint-don.spring-boot-crud-app
        container_name: clint-don.spring-boot-crud-app
        build:
            context: .
        ports:
            - 8888:8888
        depends_on:
            - spring-db
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

volumes:
    spring-boot-crud-data:
