services:
    spring-db:
        image: postgres:alpine
        container_name: egargo.spring-boot-crud-db
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_DB}
          - PGPORT=${DATABASE_PORT}
        command: postgres -c 'max_connections=1000'
        ports:
            - 5433:5432
        expose:
            - 5433
        volumes:
            - spring-boot-crud-data:/var/lib/postgresql

    spring-boot:
        image: ghcr.io/egargo/egargo.spring-boot-crud-app
        container_name: egargo.spring-boot-crud-app
        build:
            context: .
        ports:
            - 8888:8888
        depends_on:
            - spring-db
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

volumes:
    spring-boot-crud-data:
