apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  SPRING_DATASOURCE_URL:
  SPRING_DATASOURCE_USERNAME:
  SPRING_DATASOURCE_PASSWORD:
  SPRING_SECURITY_JWT_SECRET_KEY:
  SPRING_SECURITY_JWT_ACCESS_EXP:
  SPRING_SECURITY_JWT_REFRESH_EXP:
