spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: spring-docker
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
            maximum-pool-size: 1000
    data:
        web:
            pageable:
                one-indexed-parameters: true
    h2:
        console:
            enable: true
    jpa:
        database: postgresql
        properties:
            hibernate:
                boot:
                    allow_jdbc_metadata_access: false
                jdbc:
                    time_zone: Asia/Manila
        hibernate:
            ddl-auto: update
    mail:
        host: ${SPRING_MAIL_HOST}
        port: ${SPRING_MAIL_PORT}
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false
    # kafka:
    #     consumer:
    #         group-id: my-group-id
    #         bootstrap-servers: localhost:9092
    #         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #     producer:
    #         bootstrap-servers: localhost:9092
    #         key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
    port: 28279
    # port: 8888
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 2048
security:
    cors:
      allowed-origin: ${SPRING_SECURITY_CORS_ALLOWED_ORIGIN}
      allow-credentials: ${SPRING_SECURITY_CORS_ALLOW_CREDENTIALS}
      max-age: ${SPRING_SECURITY_CORS_MAX_AGE}
    jwt:
        secret-key: ${SPRING_SECURITY_JWT_SECRET_KEY}
        access-expiration-time: ${SPRING_SECURITY_JWT_ACCESS_EXP}
        refresh-expiration-time: ${SPRING_SECURITY_JWT_REFRESH_EXP}
