spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: spring-docker
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
            maximum-pool-size: 1000
    data:
        web:
            pageable:
                one-indexed-parameters: true
    h2:
        console:
            enable: true
    jpa:
        database: postgresql
        properties:
            hibernate:
                boot:
                    allow_jdbc_metadata_access: false
                jdbc:
                    time_zone: Asia/Manila
        hibernate:
            ddl-auto: update
    kafka:
        consumer:
            group-id: my-group-id
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
    port: 8888
